
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class NewJFrame1 extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }
    public int Total_Harga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        eJenis = new javax.swing.JComboBox<>();
        txtBeli = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setText("\"WELCOME TO COFFEE SHOP\"");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(68, 41, 256, 19);

        jLabel2.setText("Jenis Kopi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(63, 99, 96, 16);

        jLabel3.setText("Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(63, 139, 96, 16);

        jLabel4.setText("Jumlah Beli");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(63, 179, 96, 16);

        jLabel5.setText("Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(63, 219, 96, 16);

        jLabel6.setText("Bayar");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(63, 280, 96, 16);
        jPanel1.add(txtHarga);
        txtHarga.setBounds(188, 136, 136, 22);

        eJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kopi", "Arabica Coffee", "Robusta Coffee", "Liberian Coffee", "Excelsa Coffee" }));
        eJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJenisActionPerformed(evt);
            }
        });
        jPanel1.add(eJenis);
        eJenis.setBounds(188, 96, 136, 22);

        txtBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeliKeyReleased(evt);
            }
        });
        jPanel1.add(txtBeli);
        txtBeli.setBounds(188, 176, 136, 22);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(188, 216, 136, 22);
        jPanel1.add(txtBayar);
        txtBayar.setBounds(188, 277, 136, 22);

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung);
        btnHitung.setBounds(161, 334, 73, 23);

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(60, 334, 72, 23);

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(252, 334, 72, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJenisActionPerformed
        // TODO add your handling code here:
        if (eJenis.getSelectedItem().equals("Pilih Jenis Kopi")){
            txtHarga.setText("0");
        }else if(eJenis.getSelectedItem().equals("Arabica")){
            txtHarga.setText("15000");
        }else if(eJenis.getSelectedItem().equals("Robusta")){
            txtHarga.setText("13000");
        }else if(eJenis.getSelectedItem().equals("Liberian")){
            txtHarga.setText("12000");
        }else if(eJenis.getSelectedItem().equals("Excelsa")){
            txtHarga.setText("10000");
        }
    }//GEN-LAST:event_eJenisActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if(txtHarga.getText().isEmpty() || txtBeli.getText().isEmpty() || txtTotal.getText().isEmpty() || txtBayar.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Data Harus Diisi");
        else{
            int bayar = Integer.parseInt(txtBayar.getText());
            int kembalian = bayar - Total_Harga;
            JOptionPane.showMessageDialog(null,"Kembalian anda :\n"+kembalian);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtHarga.setText("");
        txtBeli.setText("");
        txtTotal.setText("");
        txtBayar.setText("");
        eJenis.setSelectedIndex(0);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeliKeyReleased
        // TODO add your handling code here:
        if(txtBeli.getText().equals("")){
            txtTotal.setText("0");
        }else{
            int harga = Integer.parseInt(txtHarga.getText());
            int beli = Integer.parseInt(txtBeli.getText());
            Total_Harga = harga*beli;
            txtTotal.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txtBeliKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> eJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBeli;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
